### ISSUE TITLE
Disable debugging when compiling as dependency

### ISSUE THREAD

**Issue by wojtekmach** [socialpaymentsbv/ex_phone_number#1]
When ex_phone_number is included into a project, it generates a lot of noise when compiling for the first time:

```
17:39:40.286 [debug] region_code: "SZ"

17:39:40.286 [debug] has not national_prefix

17:39:40.286 [debug] national_prefix_formatting_rule: ""

17:39:40.286 [debug] carrier_code_formatting_rule: ""

17:39:40.286 [debug] available_formats count: 1

17:39:40.287 [debug] ---> number_format

(...)
```

while this might be helpful when actively developing the library, this should be disabled by default when using it elsewhere.

**Comment by almasakchabayev** [comment]
Thank you for this lib, but I agree with  @wojtekmach. Compilation takes ages!

**Comment by josemrb** [comment]
@wojtekmach Hi, I'll look into how to disable it.
