### ISSUE TITLE
no function clause matching error??

### ISSUE THREAD

**Issue by hariharasudhan94** [socialpaymentsbv/ex_phone_number#16]
Lets say i have changeset like follow

> def changeset_user_register(struct, params \\%{}) do
    struct
    |> cast(params, [:name, :email, :countryCode, :phone])
    |> validate_required(:name, [message: "Name Must Not Be Empty"])
    |> validate_required(:countryCode, [message: "countryCode Must Not Be Empty"])
    |> validate_required(:phone, [message: "Phone Number Must Not Be Empty"])
    |> valid_phone_number
  end

 I  am trying to validate number is valid or not so created custom validation like follow
'

> defp valid_phone_number(struct) do
    countryCode = get_field(struct, :countryCode)
    phone = get_field(struct, :phone)
    {result, phone_number} = ExPhoneNumber.parse(phone, countryCode)
    if ExPhoneNumber.is_valid_number?(phone_number) do
       struct
   else
       add_error(struct, :phone, "invalid number")
    end
    struct
  end

When is run the application it shows no function clause matching in ExPhoneNumber.is_valid_number?/1

what mistake i made here?

**Comment by szymon-jez** [comment]
Do you still need help with that? If not I will close this issue.

**Comment by szymon-jez** [comment]
No communication here for a long time. Closing.
