### ISSUE TITLE
tzdata

### ISSUE THREAD

**Issue by areski** [socialpaymentsbv/ex_phone_number#21]
Hi,

Do you have any plans to support tzdata ? eg https://github.com/daviddrysdale/python-phonenumbers/blob/dev/python/phonenumbers/tzdata/data0.py

**Comment by szymon-jez** [comment]
Hello, no, we do not, but we are open to merging such feature in.

**Comment by areski** [comment]
Ok thanks for the feedback, will see what I can do for that

**Comment by szymon-jez** [comment]
The question was answered. Closing.
