### ISSUE TITLE
Add support for new metadata

### ISSUE THREAD

**Issue by brolaugh** [socialpaymentsbv/ex_phone_number#25]
Seeing as the metadata used by this library is three years old and Google is making metadata changes rather frequently is it possible that you could add support for the new metadata files? I tried your instructions in #22.
> You can try to:
> 
> 1. Replace [this file from the ex_phone_number repository](https://github.com/socialpaymentsbv/ex_phone_number/blob/b0d27690288ecca948711c572f58a9c043a80a5b/resources/PhoneNumberMetadata.xml) with [this file from google libphonenumber](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml).
> 2. Test if it works.
> 3. Add create a pull request here with the changes from point 1. We are welcome to update this.

But it 132/438 tests failed when doing so.

**Comment by JerryBels** [comment]
@brolaugh have you tried going farther than this ?

**Comment by brolaugh** [comment]
@JerryBels Yes and no. I tried looking at the code but being rather new to Elixir and coming from C# I have a hard time reading the code.

**Comment by JerryBels** [comment]
@brolaugh okay. I need something like this in my current project - will try to make it work but I have very little time to give to it.

**Comment by brolaugh** [comment]
I use the [twcclegg's C# port](https://github.com/twcclegg/libphonenumber-csharp) of Google's libphonenumber on an almost daily basis and his goal has been to keep the source code as similar to the Java code as possible. Elixir however being such a different language I believe that is very hard to do.

In order to not get overwhelmed with failed test I think a good strategy to get familiar with the library would be to test every update of metadata in chronological order and until tests brake and then fix those (hopefully) few failed tests. This might be very tedious though since Google releases new metadata on an almost weekly basis.

**Comment by josemrb** [comment]
@brolaugh 
> I use the [twcclegg's C# port](https://github.com/twcclegg/libphonenumber-csharp) of Google's libphonenumber on an almost daily basis and his goal has been to keep the source code as similar to the Java code as possible.

FYI the library is based on the JavaScript port made by Google
https://github.com/googlei18n/libphonenumber/tree/master/javascript

> In order to not get overwhelmed with failed test I think a good strategy to get familiar with the library would be to test every update of metadata in chronological order and until tests brake and then fix those (hopefully) few failed tests.

If I recall correctly the library includes the Metadata for the release 7.2.7

**Comment by brolaugh** [comment]
@josemrb Thank you for those details.

**Comment by JerryBels** [comment]
Thanks for the advices, guys, but I took it the harder but less tedious way - almost done, I think

**Comment by szymon-jez** [comment]
@JerryBels I don't know. @josemrb is the author of the first version.

**Comment by josemrb** [comment]
@JerryBels yes, it was done manually (copy/paste with regexp)
