### ISSUE TITLE
Stack smashing when compiling metadata.ex

### ISSUE THREAD

**Issue by Lida** [socialpaymentsbv/ex_phone_number#3]
I am running erlang 1:18.2 and Elixir 1.2.4 on a VirtualBox with 2GB of memory. When I try to compile this project, I get

Crash dump is being written to: erl_crash.dump...**\* stack smashing detected ***: /usr/lib/erlang/erts-7.2/bin/beam terminated

Typically this can be caused by memory pressure on the VM, but mem shows 600MB free at the time of the crash.

**Comment by josemrb** [comment]
@Lida doing a quick test looks like it needs about 1600MB free to compile `metadata.ex`

**Comment by lessless** [comment]
@josemrb that effectively means that to compile project that is using this library, server  must be able to allocate 1.6GB of free RAM during deployment?

**Comment by tomekowal** [comment]
@Lida Can you attach generated `erl_chrash.dump`. If it is not present in project working directory, try setting `ulimit -c unlimited` and compiling again.

On some Linux boxes core file size is set to 0. You can verify that by `ulimit -a`. In those cases writing crash_dump triggers stack smashing error which obscures the real problem (which might be plain old OOM)

@lessless Not exactly. It has to be able to allocate 1.6GB memory during _compilation_ which might happen on a different machine than deployment.. It is a good practice to create binaries before deployment using tools like `exrm`. This way you don't need any compile time dependencies for deployment. There is a nice series of blog posts about continues delivery with Elixir which includes section about `exrm`.

**Comment by szymon-jez** [comment]
Closing as there is no progress on this issue since years and it seams that the question asked was answered.
