### ISSUE TITLE
Adding a Changelog

### ISSUE THREAD

**Issue by tomciopp** [socialpaymentsbv/ex_phone_number#31]
It would be a nice to have a summary for any breaking changes that need to be rectified between version changes. It looks like a minor version was bumped today for formatting the codebase but I haven't checked to see if there were any API updates. A changelog would be a welcome addition.

**Comment by szymon-jez** [comment]
Thank you for raising this concern.

> It looks like a minor version was bumped today for formatting the codebase but I haven't checked to see if there were any API updates.

The API did not change. The only breaking thing which was changed is the officially supported versions of Elixir — 1.3 was removed.

> A changelog would be a welcome addition.

We already have talked about this in the team — we will start using [the GithHub repo release page](https://github.com/socialpaymentsbv/ex_phone_number/releases) as the place where the changelog (*a summary for any breaking changes that need to be rectified between version changes*) will be published.
