### ISSUE TITLE
Cache XML in ETS

### ISSUE THREAD

**Issue by lessless** [socialpaymentsbv/ex_phone_number#32]
Hi, 

I just had a quick look through library and please correct me if I'm wrong but it seems that ex_phone_number reads & parses xml file on every function call.

If this is the case and there are enough resources at your disposal it would be nice to load & parse XML only once  and query it directly from memory.

**Comment by szymon-jez** [comment]
Have you seen what things are here https://github.com/socialpaymentsbv/ex_phone_number/blob/develop/lib/ex_phone_number/metadata.ex executed at compile time (everything that is not in function definitions)? And how metaprogramming is used to write more code in the module based on the metadata?

**Comment by lessless** [comment]
Not really. Thanks for pointing it out!
