### ISSUE TITLE
Error validating Australian mobile numbers starting with 460 

### ISSUE THREAD

**Issue by ClementineOldfield** [socialpaymentsbv/ex_phone_number#34]
Any number starting with +614 60 gets validated as false, even though it is a valid Australian mobile number. 

It seems to be falsely checking a non existent region code as well as the country code (61)

**Comment by josemrb** [comment]
Yes, It was an upstream bug but was fixed in the metadata v8.10.20

I've been working on the update but it is not ready yet.

**Comment by sevenseacat** [comment]
Also having issues with Australian mobile numbers starting with 471 (ie. +61 471). Parsing the number then querying the number type returns `:unknown`, instead of `:mobile` or `:fixed_line_or_mobile`.

**Comment by szymon-jez** [comment]
Closing as this will be solved by #43.
