### ISSUE TITLE
PhoneNumberMetadata is out of date

### ISSUE THREAD

**Issue by elbasti** [socialpaymentsbv/ex_phone_number#39]
Hi all, 

We noticed PhoneNumberMetadata to be out of date for Mexican numbers. We updated a [fork](https://github.com/super-seguros/ex_phone_number/commit/ff1f4a9eb0d18135b57212a2fca52abba2d1dea7) with the Mexican metadata, but we'd love to help maintain this library.

Happy to open a PR. Should we update just the mexican data (like we did in our fork) or the entire file? Does the community have a preference?

**Comment by szymon-jez** [comment]
@josemrb is now working on an update to the last release of the v8.10.x series which makes the metadata up to date https://github.com/socialpaymentsbv/ex_phone_number/pull/33#issuecomment-565619362. Then he plans to release an update to v8.11 and v8.12 are more involved. In light of this I would wait for his work and not do a partial update for the Mexican numbers. Please stay tuned.
