### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by marcandre** [socialpaymentsbv/ex_phone_number#52]
Thanks for the great package.

Would it be possible to make frequent releases, for example when the metadata is updated? This would make it easier to manage this dependency in other projects.

**Comment by szymon-jez** [comment]
Thank you for your kind words. Please read https://github.com/socialpaymentsbv/ex_phone_number/issues/43 for an answer to your question.

_(Closing issue, because it is a duplicate)_
