### ISSUE TITLE
Validating US numbers with area code 689

### ISSUE THREAD

**Issue by NicolayD** [socialpaymentsbv/ex_phone_number#56]
Hi, thank you for the helpful library you've built. 

I stumbled upon a problem validating US phone numbers with area code 689 which seems to be a fairly new (several years old) phone area code for somewhere in Florida, at least according to [this article](https://www.mynews13.com/fl/orlando/news/2020/02/25/central-florida-689-area-code-issues). 

When I test at https://libphonenumber.appspot.com with a number such as `+16894023931` it validates it successfully, but this returns false:
```
> {:ok, parsed_phone} = ExPhoneNumber.parse("+16894023931", "US")
> ExPhoneNumber.is_valid_number?(parsed_phone)
false
```

**Comment by szymon-jez** [comment]
Thank you very much for your kind words.

Work is being done (regrettably it staled...) in #43 to address such issues like yours by updating the metadata that is used to determine if a number is valid or not etc.

Closing this issue as it will be solved by https://github.com/socialpaymentsbv/ex_phone_number/issues/43.
