### ISSUE TITLE
Tests does not run on Elixir 1.3.2

### ISSUE THREAD

**Issue by josemrb** [socialpaymentsbv/ex_phone_number#7]
It looks like the BDD framework used in the project ([Pavlov](https://github.com/sproutapp/pavlov)) has not been updated to support Elixir 1.3.2.

I'm going to switch to [ExSpec](https://github.com/drewolson/ex_spec) to be able to run the tests.

**Comment by wojtekmach** [comment]
@josemrb if it's fast & trivial to switch to exspec to just fix the build let's do that. if it's non-trivial, imo let's discuss switching to ExUnit which is used in the vast majority of elixir projects.

**Comment by zoldar** [comment]
@wojtekmach He already prepared a switch to exspec: https://github.com/socialpaymentsbv/ex_phone_number/pull/8

**Comment by wojtekmach** [comment]
@zoldar ugh, that's right. thanks and sorry for noise :)
